services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=${LOCAL_USER}
      - POSTGRESQL_PASSWORD=${LOCAL_PASSWORD}
      - POSTGRESQL_DATABASE=${LOCAL_DATABASE}
