services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=${LOCAL_USER}
      - POSTGRESQL_PASSWORD=${LOCAL_PASSWORD}
      - POSTGRESQL_DATABASE=${LOCAL_DATABASE}
    volumes:
      - postgres_data:/bitnami/postgresql
    restart: unless-stopped
volumes:
  postgres_data:
